import * as ActionTypes from './ActionTypes';

export const Comments = (state = {
    errMess: null,
    comments: []
    }, action) => {
    switch(action.type) {
        case ActionTypes.ADD_COMMENTS:
            return {...state, isLoading: false, errMess: null, comments: action.payload};

        case ActionTypes.COMMENTS_FAILED:
            return {...state, isLoading: false, errMess: action.payload, comments: []};

        case ActionTypes.ADD_COMMENT:
            var comment = action.payload;
            // comment.id = state.comments.length; // This is already generated by the server
            // comment.date = new Date().toISOString(); // We changed this to be added in the add comments action in ActionCreator.js
            return {...state, comments: state.comments.concat(comment)};

        default:
            return state;
    }
}